/* EVio frontend + dependency-free backend client. Chatbot backend remains external. */
const CHATBOT_URL = "PASTE_YOUR_CHATBOT_URL_HERE";
const API = "/api";
const pages={chatbot:["EVIO / GUIDE","Meet EVio"],quiz:["EVIO / MAJOR ADVISOR","Majors Quiz"],dashboard:["EVIO / YOUR SPACE","Dashboard"],scholarships:["EVIO / RESOURCE HUB","Scholarships"],planner:["EVIO / PRODUCTIVITY","Academic Planner"],settings:["EVIO / PREFERENCES","Settings"]};
const navItems=document.querySelectorAll(".nav-item"),pageEls=document.querySelectorAll(".page"),title=document.getElementById("pageTitle"),eyebrow=document.getElementById("pageEyebrow"),sidebar=document.getElementById("sidebar"),overlay=document.getElementById("sidebarOverlay");
async function api(path,options={}){const res=await fetch(`${API}${path}`,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});if(!res.ok)throw new Error((await res.json().catch(()=>({}))).error||`API error ${res.status}`);return res.status===204?null:res.json();}
function showPage(page,updateHash=true){if(!pages[page])page="chatbot";pageEls.forEach(el=>el.classList.toggle("active",el.id===`page-${page}`));navItems.forEach(btn=>btn.classList.toggle("active",btn.dataset.page===page));eyebrow.textContent=pages[page][0];title.textContent=pages[page][1];if(updateHash)history.replaceState(null,"",`#${page}`);sidebar.classList.remove("open");overlay.classList.remove("show");window.scrollTo({top:0,behavior:document.body.classList.contains("reduced-motion")?"auto":"smooth"});if(page==='dashboard')loadDashboard();if(page==='scholarships')loadResources();if(page==='planner')loadPlanner();if(page==='settings')loadSettings();}
navItems.forEach(btn=>btn.addEventListener("click",()=>showPage(btn.dataset.page)));document.querySelectorAll("[data-page-jump]").forEach(btn=>btn.addEventListener("click",()=>showPage(btn.dataset.pageJump)));document.getElementById("openSidebar").addEventListener("click",()=>{sidebar.classList.add("open");overlay.classList.add("show")});document.getElementById("closeSidebar").addEventListener("click",()=>{sidebar.classList.remove("open");overlay.classList.remove("show")});overlay.addEventListener("click",()=>{sidebar.classList.remove("open");overlay.classList.remove("show")});
const frame=document.getElementById("chatbotFrame"),placeholder=document.getElementById("iframePlaceholder");if(CHATBOT_URL&&!CHATBOT_URL.includes("PASTE_YOUR")){frame.src=CHATBOT_URL;placeholder.style.display="none";}document.querySelectorAll(".prompt-row button").forEach(btn=>btn.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(btn.dataset.prompt);toast("Prompt copied — paste it into EVio.")}catch{toast(btn.dataset.prompt)}}));

// ---------- Major advisor: randomized 24-question sample from a 506-question bank ----------
let quizQuestions=[],qIndex=0,answers=[];const qEl=document.getElementById("quizQuestion"),stepEl=document.getElementById("quizStep"),pctEl=document.getElementById("quizPercent"),bar=document.getElementById("quizBar"),nextBtn=document.getElementById("quizNext");
async function startQuiz(){try{const data=await api("/quiz/questions?count=24");quizQuestions=data.questions;answers=Array(quizQuestions.length).fill(null);qIndex=0;document.getElementById("quizCountBadge").textContent=`24 questions · ${data.totalAvailable} available`;renderQuestion();}catch{toast("Couldn't load the major assessment.")}}
function renderQuestion(){const item=quizQuestions[qIndex];if(!item)return;const pct=Math.round(((qIndex+1)/quizQuestions.length)*100);stepEl.textContent=`Question ${qIndex+1} of ${quizQuestions.length}`;pctEl.textContent=`${pct}%`;bar.style.width=pct+"%";qEl.innerHTML=`<div class="question-number">QUESTION ${String(qIndex+1).padStart(2,"0")}</div><div class="question-title">${item.q}</div><div class="answer-grid">${item.a.map((x,i)=>`<button class="answer-option ${answers[qIndex]===i?'selected':''}" data-answer="${i}"><strong>${x.text}</strong><small>Choose this if it sounds most like you.</small></button>`).join("")}</div>`;qEl.querySelectorAll(".answer-option").forEach(b=>b.addEventListener("click",()=>{answers[qIndex]=+b.dataset.answer;renderQuestion()}));document.getElementById("quizBack").disabled=qIndex===0;nextBtn.textContent=qIndex===quizQuestions.length-1?"Get my recommendation →":"Next →";}
document.getElementById("quizBack").addEventListener("click",()=>{if(qIndex>0){qIndex--;renderQuestion()}});nextBtn.addEventListener("click",async()=>{if(answers[qIndex]===null){toast("Choose an option first.");return}if(qIndex<quizQuestions.length-1){qIndex++;renderQuestion();return}try{const result=await api("/quiz/results",{method:"POST",body:JSON.stringify({answers:answers.map((optionIndex,i)=>({questionId:quizQuestions[i].id,optionIndex}))})});qEl.innerHTML=`<div class="question-number">YOUR EVIO MATCH</div><div class="question-title">Explore <em style="color:var(--pink)">${result.recommendation}</em>.</div><p class="result-copy">Your strongest match is based on ${result.questionCount} answers and compared against multiple major profiles. Here are your top pathways:</p><div class="result-list">${result.top.map(x=>`<div><strong>${x.major}</strong><span>${x.match}% relative match</span></div>`).join("")}</div><div style="margin-top:25px"><button class="btn btn-primary" id="restartQuiz">Retake assessment</button></div>`;nextBtn.style.display="none";toast("Your major exploration profile is saved.");document.getElementById("restartQuiz").addEventListener("click",()=>{nextBtn.style.display="inline-flex";startQuiz();});loadDashboard();}catch{toast("Couldn't save your assessment.");}});

let resources=[];async function loadResources(){try{resources=await api("/resources");renderResources()}catch{toast("Couldn't load resources from the backend.")}}function renderResources(){const grid=document.getElementById("resourceGrid");if(!grid)return;grid.innerHTML=resources.map(r=>`<article class="resource-card" data-category="${r.category}"><span class="resource-label ${r.category==='financial'?'green':r.category==='applications'?'pink':'gold'}">${r.label}</span><h3>${r.title}</h3><p>${r.description}</p><button class="text-btn" data-resource-url="${r.url}" data-resource-id="${r.id}">Open resource →</button></article>`).join("");filterResources();grid.querySelectorAll("[data-resource-url]").forEach(b=>b.addEventListener("click",async()=>{window.open(b.dataset.resourceUrl,"_blank","noopener,noreferrer");await api("/explore/event",{method:"POST",body:JSON.stringify({category:"resources",action:`opened ${b.dataset.resourceId}`})}).catch(()=>{});}))}const search=document.getElementById("scholarshipSearch"),filters=document.querySelectorAll(".filter");function filterResources(){const query=(search.value||"").toLowerCase(),active=document.querySelector(".filter.active")?.dataset.filter||"all";document.querySelectorAll(".resource-card").forEach(card=>{const category=card.dataset.category;const okFilter=active==='all'||(active==='aid'&&category==='financial')||(active==='scholarship'&&category==='applications')||(active==='planning'&&(category==='college'||category==='financial'));card.style.display=okFilter&&(!query||card.textContent.toLowerCase().includes(query))?"block":"none"})}filters.forEach(f=>f.addEventListener("click",()=>{filters.forEach(x=>x.classList.remove("active"));f.classList.add("active");filterResources()}));search.addEventListener("input",filterResources);

async function loadDashboard(){try{const d=await api("/dashboard");const stats=document.querySelectorAll(".stat-card");document.querySelector(".streak strong").textContent=d.stats.streak;if(stats[0]){stats[0].querySelector("strong").textContent=d.stats.applicationProgress+"%";stats[0].querySelector(".mini-progress i").style.width=d.stats.applicationProgress+"%";}if(stats[1]){stats[1].querySelector("strong").textContent=d.stats.weeklyHours+"h";stats[1].querySelector("small").textContent=`of ${d.stats.weeklyGoal}h this week`;stats[1].querySelector(".ring-line i").style.width=d.stats.weeklyProgress+"%";}if(stats[2])stats[2].querySelector("strong").textContent=d.stats.exploreScore;const remaining=d.tasks.filter(t=>!t.done).length;if(stats[3])stats[3].querySelector("strong").textContent=remaining;renderDashboardTasks(d.tasks);renderApplication(d.application);renderStudy(d.stats);renderExplore(d.explore);}catch{}}
function renderDashboardTasks(tasks){const panel=document.querySelector("#page-dashboard .dashboard-grid .panel");if(!panel)return;const heading=panel.querySelector(".panel-heading");panel.innerHTML="";panel.appendChild(heading);tasks.slice(0,3).forEach(t=>{const row=document.createElement("div");row.className=`task ${t.done?'done':''}`;row.innerHTML=`<button class="check" aria-label="Toggle ${t.title}">${t.done?'✓':''}</button><div><strong>${t.title}</strong><small>${t.meta} · ${t.due}</small></div><span class="task-tag">${t.done?'Done':t.tag}</span>`;row.querySelector(".check").addEventListener("click",()=>toggleTask(t));panel.appendChild(row)})}
async function toggleTask(t){await api(`/tasks/${t.id}`,{method:"PATCH",body:JSON.stringify({done:!t.done})});toast(t.done?"Task reopened.":"Task completed ✦");loadDashboard();loadPlanner()}
function renderApplication(app){const pct=Math.round(app.steps.filter(s=>s.done).length/app.steps.length*100);document.getElementById("applicationProgressBadge").textContent=pct+"%";document.getElementById("applicationProgressBar").style.width=pct+"%";document.getElementById("applicationChecklist").innerHTML=app.steps.map(s=>`<label class="application-step ${s.done?'done':''}"><input type="checkbox" ${s.done?'checked':''} data-app-step="${s.id}"><span><strong>${s.title}</strong><small>${s.category}</small></span></label>`).join("");document.querySelectorAll("[data-app-step]").forEach(c=>c.addEventListener("change",async()=>{await api(`/application/${c.dataset.appStep}`,{method:"PATCH",body:JSON.stringify({done:c.checked})});toast(c.checked?"Application step completed.":"Application step reopened.");loadDashboard();}))}
function renderStudy(stats){const d=document.getElementById("dailyStudyGoal"),w=document.getElementById("weeklyStudyGoal");if(d)d.value=stats.dailyGoal;if(w)w.value=stats.weeklyGoal;document.getElementById("studyGoalSummary").innerHTML=`<div><strong>${stats.dailyHours.toFixed(2)}h / ${stats.dailyGoal}h</strong><small>today · ${stats.dailyProgress}%</small></div><div><strong>${stats.weeklyHours.toFixed(2)}h / ${stats.weeklyGoal}h</strong><small>this week · ${stats.weeklyProgress}%</small></div>`}
document.getElementById("saveStudyGoals").addEventListener("click",async()=>{await api("/study",{method:"PUT",body:JSON.stringify({dailyGoal:document.getElementById("dailyStudyGoal").value,weeklyGoal:document.getElementById("weeklyStudyGoal").value})});toast("Study goals updated.");loadDashboard()});document.getElementById("logStudyHours").addEventListener("click",async()=>{const v=document.getElementById("studyHoursLog").value;if(!v)return toast("Enter the hours you studied.");await api("/study/log",{method:"POST",body:JSON.stringify({hours:v})});document.getElementById("studyHoursLog").value="";toast("Study time logged ✦");loadDashboard()});
function renderExplore(data){document.getElementById("dashboardExploreScore").textContent=data.score;document.getElementById("exploreScoreBar").style.width=data.score+"%";const counts=data.categories||{};document.getElementById("exploreCategories").innerHTML=[['major','Major'],['college','College'],['application','Application'],['resources','Resources'],['planning','Planning']].map(([k,l])=>`<span><strong>${l}</strong><small>${counts[k]||0} activities</small></span>`).join("");document.getElementById("exploreNextGrid").innerHTML=data.recommendations.map(item=>`<button class="explore-next-card" data-explore-action="${item.action||'quiz'}"><span class="rec-icon ${item.id==='college'?'pink':item.id==='application'?'gold':''}">${item.id==='major'?'⌁':item.id==='college'?'◇':'✦'}</span><span><strong>${item.title}</strong><small>${item.desc}</small></span><b>${item.score>=100?'✓':'→'}</b></button>`).join("");document.querySelectorAll("[data-explore-action]").forEach(b=>b.addEventListener("click",()=>{const action=b.dataset.exploreAction;if(action==='quiz'){showPage('quiz');startQuiz();}else openExploreModal(action);}));}
function openExploreModal(kind){const backdrop=document.getElementById("modalBackdrop"),content=document.getElementById("modalContent");backdrop.classList.add("show");if(kind==='college-fit'){content.innerHTML=`<div class="modal-head"><div><span class="kicker">COLLEGE FIT</span><h3>What matters most to you?</h3></div><button class="icon-btn" data-close-modal>×</button></div><p>Rate each factor from 1 to 5 based on how important it is in your ideal college.</p><div class="fit-grid">${[['size','Campus size'],['location','Location'],['cost','Cost'],['culture','Campus culture'],['programs','Programs/majors']].map(([k,l])=>`<label>${l}<input type="range" min="1" max="5" value="3" data-fit="${k}"><span class="range-value">3</span></label>`).join("")}</div><button class="btn btn-primary" id="saveCollegeFit">Save college fit</button>`;content.querySelectorAll("[data-fit]").forEach(r=>r.addEventListener("input",()=>r.nextElementSibling.textContent=r.value));document.getElementById("saveCollegeFit").addEventListener("click",async()=>{const body={};content.querySelectorAll("[data-fit]").forEach(r=>body[r.dataset.fit]=r.value);await api("/explore/college-fit",{method:"POST",body:JSON.stringify(body)});closeModal();toast("College fit profile saved ✦");loadDashboard();});}else{content.innerHTML=`<div class="modal-head"><div><span class="kicker">APPLICATION STORY</span><h3>Build your story</h3></div><button class="icon-btn" data-close-modal>×</button></div><p>Write a few sentences for each prompt. EVio will save your responses so you can revisit them while working on applications.</p><div class="story-fields"><label>Experience<textarea data-story="experience" placeholder="What experience mattered to you?"></textarea></label><label>Growth<textarea data-story="growth" placeholder="How did it change you?"></textarea></label><label>Impact<textarea data-story="impact" placeholder="Who or what did you affect?"></textarea></label><label>Future<textarea data-story="future" placeholder="How does it connect to where you are going?"></textarea></label></div><button class="btn btn-primary" id="saveApplicationStory">Save application story</button>`;document.getElementById("saveApplicationStory").addEventListener("click",async()=>{const body={};content.querySelectorAll("[data-story]").forEach(x=>body[x.dataset.story]=x.value);try{await api("/explore/application-story",{method:"POST",body:JSON.stringify(body)});closeModal();toast("Application story saved ✦");loadDashboard();}catch(e){toast(e.message)}});}}
function closeModal(){document.getElementById("modalBackdrop").classList.remove("show")}document.getElementById("modalBackdrop").addEventListener("click",e=>{if(e.target.id==='modalBackdrop'||e.target.closest('[data-close-modal]'))closeModal()});

async function loadPlanner(){try{const [tasks,schedule,goals]=await Promise.all([api("/tasks"),api("/schedule"),api("/goals")]);renderPlannerTasks(tasks);renderSchedule(schedule);renderGoals(goals)}catch{}}
function renderPlannerTasks(tasks){const panel=document.querySelector("#page-planner .calendar-panel");if(!panel)return;let box=panel.querySelector(".planner-tasks");if(!box){box=document.createElement("div");box.className="planner-tasks";panel.appendChild(box)}box.innerHTML=`<div class="panel-heading"><div><span class="kicker">TASKS</span><h3>Your assignments</h3></div></div>`+tasks.map(t=>`<div class="task ${t.done?'done':''}" data-task-id="${t.id}"><button class="check">${t.done?'✓':''}</button><div><strong>${t.title}</strong><small>${t.meta} · ${t.due}</small></div><button class="text-btn delete-task">Delete</button></div>`).join("");box.querySelectorAll(".check").forEach((b,i)=>b.addEventListener("click",()=>toggleTask(tasks[i])));box.querySelectorAll(".delete-task").forEach((b,i)=>b.addEventListener("click",async()=>{await api(`/tasks/${tasks[i].id}`,{method:"DELETE"});toast("Task deleted.");loadPlanner();loadDashboard()}))}
function renderSchedule(items){const el=document.querySelector("#page-planner .schedule");if(!el)return;el.innerHTML=items.map(x=>`<div class="schedule-item"><time>${x.time}</time><div class="schedule-bar ${x.tone}-bar"><strong>${x.title}</strong><small>${x.meta}</small></div></div>`).join("")}
function renderGoals(goals){const panel=document.querySelector("#page-planner .goals-panel");if(!panel)return;const timer=panel.querySelector(".pomodoro");panel.querySelectorAll(".goal").forEach(x=>x.remove());goals.forEach(g=>{const el=document.createElement("div");el.className="goal";el.innerHTML=`<div class="goal-ring">${g.progress}%</div><div><strong>${g.title}</strong><small>Weekly progress</small></div>`;panel.insertBefore(el,timer);});}
document.getElementById("addTaskBtn").addEventListener("click",async()=>{const t=prompt("Task name:");if(!t?.trim())return;const due=prompt("Due label (e.g. Friday, Tomorrow):","This week")||"This week";await api("/tasks",{method:"POST",body:JSON.stringify({title:t.trim(),due})});toast("Task added to your planner.");loadPlanner();loadDashboard()});
let timerRunning=false,timerSeconds=1500,timerInterval;const timerBtn=document.getElementById("timerBtn");timerBtn.addEventListener("click",()=>{if(timerRunning){clearInterval(timerInterval);timerRunning=false;timerBtn.textContent="Start";return}timerRunning=true;timerBtn.textContent="Pause";timerInterval=setInterval(()=>{timerSeconds--;if(timerSeconds<=0){clearInterval(timerInterval);timerRunning=false;timerBtn.textContent="Start";timerSeconds=1500;toast("Focus session complete ✦");api("/study/log",{method:"POST",body:JSON.stringify({hours:0.4167})}).then(loadDashboard).catch(()=>{});}const m=String(Math.floor(timerSeconds/60)).padStart(2,"0"),s=String(timerSeconds%60).padStart(2,"0");document.querySelector(".pomodoro small").textContent=`${m}:${s} · focus session`},1000)});

// ---------- Settings + 21 working themes ----------
const themes=[
['firefly-dark','Firefly Dark','#07120f','#9fe1ad','#f58cae'],['moonlit-rose','Moonlit Rose','#140d16','#e7b7d4','#ff7fae'],['mint-noir','Mint Noir','#071713','#86e6c0','#a9f0cf'],['lavender-night','Lavender Night','#100d1a','#c3b5ff','#f39ad2'],['ocean-pink','Ocean Pink','#07141b','#8ed7e8','#f29bc1'],['sage-dream','Sage Dream','#10170f','#b9df9f','#f3b2c5'],['peach-moss','Peach Moss','#17120d','#b9d79a','#ffb38f'],['strawberry-leaf','Strawberry Leaf','#180d12','#b8e3ae','#ff8eae'],['bluebell-glow','Bluebell Glow','#0c1020','#9fbaff','#eaa5d6'],['emerald-dusk','Emerald Dusk','#06140f','#73d99b','#d7efae'],['plum-firefly','Plum Firefly','#160b17','#c6a2e8','#f28bb1'],['forest-sunset','Forest Sunset','#11140d','#b6db9a','#ffb06e'],['teal-orchid','Teal Orchid','#071619','#7edbd3','#e9a6df'],['rosewood','Rosewood','#170f10','#e1a6a1','#f49ab4'],['arctic-mint','Arctic Mint','#09161a','#a6e6dc','#c3f1a8'],['cosmic-pink','Cosmic Pink','#0e0b18','#bca9ff','#ff86bd'],['citrus-night','Citrus Night','#11150b','#d4e78d','#ff9e9e'],['lavender-mint','Lavender Mint','#0d1117','#b9e4c8','#d1a9ff'],['rose-gold','Rose Gold','#160f0e','#f2c18f','#f28fae'],['deep-sea','Deep Sea','#061117','#76c8d9','#e89fbf'],['meadow-night','Meadow Night','#0a150f','#a9e5a0','#f2c7a0']];
function applyTheme(theme){const t=themes.find(x=>x[0]===theme)||themes[0];document.documentElement.style.setProperty('--bg',t[2]);document.documentElement.style.setProperty('--green',t[3]);document.documentElement.style.setProperty('--pink',t[4]);document.body.dataset.theme=theme;document.querySelectorAll('.theme-card').forEach(c=>c.classList.toggle('selected',c.dataset.theme===theme));}
async function saveSetting(key,value){try{const s=await api('/settings',{method:'PUT',body:JSON.stringify({[key]:value})});applySettings(s);}catch{toast("Couldn't save that preference.")}}
function applySettings(settings){if(!settings)return;applyTheme(settings.theme||'firefly-dark');document.body.classList.toggle('reduced-motion',!!settings.reducedMotion);document.body.classList.toggle('large-text',!!settings.largerText||settings.fontSize==='large');document.body.classList.toggle('high-contrast',!!settings.highContrast);document.body.classList.toggle('reduced-transparency',!!settings.reducedTransparency);document.body.classList.toggle('reduced-flashing',!!settings.reducedFlashing);document.body.classList.toggle('compact-mode',!!settings.compactMode||settings.density==='compact');document.body.classList.toggle('no-background-effects',settings.backgroundEffects===false);document.body.classList.toggle('strong-focus',settings.focusIndicators!==false);document.querySelectorAll('.toggle[data-setting-key]').forEach(t=>{const k=t.dataset.settingKey;if(settings[k]!==undefined)t.classList.toggle('on',!!settings[k]);});document.querySelectorAll('[data-setting-input]').forEach(el=>{const k=el.dataset.settingInput;if(settings[k]!==undefined)el.value=settings[k];});if(settings.glowIntensity==='off')document.body.classList.add('no-glow');else document.body.classList.remove('no-glow');}
function loadSettings(){api('/state').then(s=>{applySettings(s.settings);renderThemes(s.settings.theme)}).catch(()=>{})}
function renderThemes(active){const grid=document.getElementById('themeGrid');if(!grid)return;grid.innerHTML=themes.map(t=>`<button class="theme-card ${t[0]===active?'selected':''}" data-theme="${t[0]}"><span class="theme-swatch" style="--sw-bg:${t[1]};--sw-green:${t[3]};--sw-pink:${t[4]}"></span><strong>${t[1]}</strong><small>${t[0].replaceAll('-',' ')}</small><b>✓</b></button>`).join('');grid.querySelectorAll('.theme-card').forEach(b=>b.addEventListener('click',()=>saveSetting('theme',b.dataset.theme)));}
document.querySelectorAll('.setting-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.setting-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.setting-pane').forEach(x=>x.classList.remove('active'));tab.classList.add('active');document.getElementById(`setting-${tab.dataset.setting}`).classList.add('active');}));
document.querySelectorAll('.toggle').forEach(t=>t.addEventListener('click',()=>{const k=t.dataset.settingKey;saveSetting(k,!t.classList.contains('on'));}));document.querySelectorAll('[data-setting-input]').forEach(el=>el.addEventListener('change',()=>saveSetting(el.dataset.settingInput,el.value)));

function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2600)}
async function boot(){try{const state=await api('/state');applySettings(state.settings);loadDashboard();loadResources();loadPlanner();renderThemes(state.settings.theme);}catch{toast("EVio backend is not running. Start it with npm start.")}}
const initial=(location.hash||'#chatbot').slice(1);showPage(pages[initial]?initial:'chatbot',false);boot();
